taller_manto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utaller.urls')),

]

utaller/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[ 
    path ('',views.gestionex, name = 'index',),
    path ('Header/',views.Header, name = 'Header',),

    path ('gestionex/', views.gestionex, name='gestionex',),    
    path('reportes/', views.reportes, name='reportes'),
    path ('entrada/', views.entrada, name='entrada',),
    path ('salida/', views.salida, name='salida',),
    path('orden_salida/', views.orden_salida, name='orden_salida'),
    path ('facturas/', views.facturas, name='facturas',),

    path ('login/', views.login, name='login',),
    path ('registro/', views.registro, name='registro',),
    path ('aviso/', views.aviso, name='aviso',),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utaller/models.py
from django.db import models
from django.contrib import admin
import bcrypt
from django_otp.models import SideChannelDevice
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UsuariosGenerales(models.Model):
    nombre_de_usuario = models.CharField(max_length=150, unique=True)
    nombre= models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100) 
    apellido_materno = models.CharField(max_length=100)
    correo_electronico = models.EmailField(unique=True)  # Nuevo campo para el correo electrónico
    telefono = models.PositiveIntegerField()
    contraseña_hash = models.CharField(max_length=128)  
    activo = models.BooleanField(default=False)  # Por defecto, el usuario estará inactivo
    otp_secret = models.CharField(max_length=16, blank=True, null=True)
    otp_enabled = models.BooleanField(default=False)

    def enable_otp(self):
        device = SideChannelDevice.objects.create(user=self)
        self.otp_secret = device.bin_key
        self.otp_enabled = True
        self.save()

    def disable_otp(self):
        self.otp_secret = None
        self.otp_enabled = False
        self.save()

    def __str__(self):
        return self.nombre

    def set_password(self, raw_password):
        # Genera el hash de la contraseña utilizando bcrypt
        self.contraseña_hash = bcrypt.hashpw(raw_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    def check_password(self, raw_password):
        # Verifica si la contraseña proporcionada coincide con la contraseña almacenada
        return bcrypt.checkpw(raw_password.encode('utf-8'), self.contraseña_hash.encode('utf-8'))


@receiver(post_save, sender=User)
def set_user_inactive(sender, instance, created, **kwargs):
    if created:
        instance.activo = False
        instance.save()

#--------------------------------------------------------------------
CATEGORIAS = [
    ('refacciones', 'Refacciones'),
    ('herramientas', 'Herramientas'),
    ('aceites', 'Aceites'),
    ('filtros', 'Filtros'),
    ('llantas', 'Llantas'),
    ('combustible', 'Combustible'),
]

# Definir las opciones para las unidades de medida
UNIDADES_DE_MEDIDA = [
    ('pieza', 'Pieza'),
    ('metro', 'Metro'),
    ('gramo', 'Gramo'),
    ('kilogramo', 'Kilogramo'),
    ('litro', 'Litro'),
]

DEPARTAMENTOS = [
    ('limpia_pública',  'Limpia Pública'),
    ('maquinaria_pesada',  'Maquinaria Pesada'),
    ('obras_públicas',  'Obras Públicas'),
    ('ornatos', 'Ornatos'),
    ('policía_municipal', 'Policía Municipal'),
    ('presidencia', 'Presidencia'),
    ('protección_civil', 'Protección Civil'),
    ('recursos_humanos', 'Recursos Humanos'),
    ('infraestructura_urbana', 'Infraestructura Urbana'),
    ('gobierno', 'Gobierno'),
    ('dirección_de_ingresos', 'Dirección De Ingresos'),
    ('dirección_de_gobernación', 'Dirección De Gobernación'),
    ('dif_municipal', 'Dif Municipal'),
    ('desarrollo_urbano_y_medio_ambiente', 'Desarrollo Urbano Y Medio Ambiente'),
    ('comunicación_social', 'Comunicación Social'),
    ('alumbrado_público', 'Alumbrado Público'),
    ('basurero_municipal', 'Basurero Municipal'),
    ('atención_y_participación_ciudadana', 'Atención Y Participación Ciudadana'),
    ('agencia_municipal_de_mundo_nuevo', 'Agencia Municipal De Mundo Nuevo'),
    ('acción_social', 'Acción Social'),
]

from django.utils import timezone

class Inventario(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.CharField(max_length=20, choices=CATEGORIAS)
    unidad_de_medida = models.CharField(max_length=20, choices=UNIDADES_DE_MEDIDA)
    cantidad_disponible = models.PositiveIntegerField(default=0)
    ultima_modificacion = models.DateTimeField(default=timezone.now)  # Nuevo campo para la última modificación

    def __str__(self):
        return self.nombre

#---------------------------------------------------------------------------------------
class EntradaArticulo(models.Model):
    nombre_de_articulo = models.CharField(max_length=100)
    categoria = models.CharField(max_length=20, choices=CATEGORIAS)
    unidad_de_medida = models.CharField(max_length=20, choices=UNIDADES_DE_MEDIDA)
    cantidad_disponible = models.PositiveIntegerField()
    fecha_y_hora = models.DateTimeField(default=timezone.now)  # Asigna un valor por defecto

    def __str__(self):
        return f"{self.nombre_de_articulo} - {self.fecha_y_hora.strftime}"
    
    def save(self, *args, **kwargs):
        inventario, created = Inventario.objects.get_or_create(
            nombre=self.nombre_de_articulo, categoria=self.categoria, unidad_de_medida=self.unidad_de_medida)
        inventario.cantidad_disponible += self.cantidad_disponible
        inventario.ultima_modificacion = timezone.now()  # Actualizar la fecha y hora de la última modificación
        inventario.save()
        super().save(*args, **kwargs)

#---------------------------------------------------------------------------------------

class SalidaArticulo(models.Model):
    nombre_de_articulo = models.ForeignKey(Inventario, on_delete=models.CASCADE, blank=True,null=True)
    numero_orden = models.CharField(max_length=100)
    unidad = models.CharField(max_length=100)
    cantidad = models.PositiveIntegerField()
    departamento = models.CharField(max_length=100, choices=DEPARTAMENTOS)
    fecha_y_hora_salida = models.DateTimeField(default=timezone.now)  # Asigna un valor por defecto

    def __str__(self):
        return f"Orden {self.numero_orden} - {self.fecha_y_hora_salida.strftime}"
    
    def save(self, *args, **kwargs):
        Inventario = self.nombre_de_articulo  # Aquí es donde hacemos el ajuste
        if Inventario.cantidad_disponible  < self.cantidad:
            raise ValueError("No hay suficiente cantidad en inventario.")
        Inventario.cantidad_disponible -= self.cantidad
        Inventario.ultima_modificacion = timezone.now()  # Actualizar la fecha y hora de la última modificación
        Inventario.save()
        super().save(*args, **kwargs)
        
#---------------------------------------------------------------------------------------

class OrdenSalida(models.Model):
    nombre_de_articulo = models.ForeignKey(Inventario, on_delete=models.CASCADE)
    numero_orden = models.CharField(max_length=100)
    unidad = models.CharField(max_length=100)
    cantidad = models.PositiveIntegerField()
    fecha_y_hora = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Orden {self.numero_orden} - {self.fecha_y_hora.strftime}"
    def save(self, *args, **kwargs):
        inventario = self.nombre_de_articulo
        if inventario.cantidad_disponible < self.cantidad:
            raise ValueError("No hay suficiente cantidad en inventario.")
        super().save(*args, **kwargs)


#---------------------------------------------------------------------------------------
class Factura(models.Model):
    clave_de_registro = models.CharField(max_length=100)
    numero_de_folio = models.CharField(max_length=100)
    concepto = models.CharField(max_length=100)
    fecha_de_factura = models.DateField()
    archivo = models.FileField(upload_to='facturas/')

    def __str__(self):
        return f'Factura {self.numero_de_folio} - {self.concepto}'
    
#---------------------------------------------------------------------------------------
class Reportes(models.Model):
    clave_de_registro = models.CharField(max_length=100)
    numero_de_folio = models.CharField(max_length=100)
    concepto = models.CharField(max_length=100)
    fecha_de_reportes = models.DateField()
    archivo = models.FileField(upload_to='reportes/')

    def __str__(self):
        return f'Reportes {self.numero_de_folio} - {self.concepto}'

utaller/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect  # Agregamos la importación de redirect
from .models import UsuariosGenerales
from django.contrib import messages
from .forms import UsuariosForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def login(request):
    if request.method == 'POST':
        nombre_de_usuario = request.POST.get('nombre_de_usuario')
        contraseña = request.POST.get('contraseña')
        # Verificar si el usuario existe en la base de datos
        try:
            usuario = UsuariosGenerales.objects.get(nombre_de_usuario=nombre_de_usuario)
            if usuario.check_password(contraseña):
                if usuario.activo:
                    request.session['usuario_id'] = usuario.id
                    return redirect('index') 
                else:
                    return redirect('aviso')
            else:
                messages.error(request, 'Contraseña incorrecta.')
        except UsuariosGenerales.DoesNotExist:
            messages.error(request, 'El usuario no existe.')
    return render(request, 'login.html')
#----------------------------------------------------------------

def registro(request):
    if request.method == 'POST':  # Verifica si se ha enviado un formulario
        form = UsuariosForm(request.POST)  # Inicializa el formulario con los datos recibidos
        if form.is_valid():  # Valida el formulario
            nombre_de_usuario = form.cleaned_data['nombre_de_usuario']
            if User.objects.filter(username=nombre_de_usuario).exists():
                messages.error(request, '¡El usuario ya existe! Por favor, elige otro nombre de usuario.')
            else:
                usuario = form.save(commit=False)
                usuario.set_password(form.cleaned_data['contraseña'])
                usuario.save()
                messages.success(request, '¡Usuario creado con éxito!')
                return redirect('registro')
        else:
            messages.error(request, '¡Error en el formulario! Por favor, corrige los errores e intenta nuevamente.')  # Muestra un mensaje de error
    else:
        form = UsuariosForm()  # Crea un formulario vacío si la solicitud no es de tipo POST
    return render(request, 'registro.html', {'form': form})  # Renderiza la plantilla con el formulario

#------------------------------------------------------------------

from .models import EntradaArticulo, SalidaArticulo, Inventario
from .forms import SalidaArticuloForm
from .forms import EntradaArticuloForm
from django.db.models import Q

def gestionex(request):
    query = request.GET.get('q')
    
    if query:
        inventario = Inventario.objects.filter(
            Q(nombre__icontains=query) |
            Q(categoria__icontains=query) |
            Q(unidad_de_medida__icontains=query)
        ).order_by('-ultima_modificacion')
    else:
        inventario = Inventario.objects.all().order_by('-ultima_modificacion')
    
    return render(request, 'gestionex.html', {'inventario': inventario, 'search_query': query})
#------------------------------------------------------------------
from django.db.models import Q

def entrada(request):
    query = request.GET.get('q')
    entradas = EntradaArticulo.objects.all().order_by('-fecha_y_hora')  # Ordenar por fecha y hora en orden descendente
    if query:
        entradas = entradas.filter(
            Q(nombre_de_articulo__icontains=query) |
            Q(categoria__icontains=query) |
            Q(unidad_de_medida__icontains=query)
        )
    if request.method == 'POST':
        form = EntradaArticuloForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Artículo agregado con éxito')
            return redirect('entrada')
        else:
            messages.error(request, 'Error al agregar el artículo. Por favor, verifica el formulario.')
    else:
        form = EntradaArticuloForm()
    return render(request, 'entrada.html', {'form': form, 'entradas': entradas, 'search_query': query})

#------------------------------------------------------------------

def salida(request):
    query = request.GET.get('q')
    salidas = SalidaArticulo.objects.all().order_by('-fecha_y_hora_salida')
    if query:
        salidas = salidas.filter(
            Q(nombre_de_articulo__nombre__icontains=query) |  # Buscar en el nombre del artículo
            Q(numero_orden__icontains=query) |                # Buscar en el número de orden
            Q(unidad__icontains=query) |                      # Buscar en la unidad
            Q(departamento__icontains=query)
        )
    if request.method == 'POST':
        form = SalidaArticuloForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'Salida registrada con éxito.')
                return redirect('salida')
            except ValueError as e:
                form.add_error(None, str(e))
                messages.error(request, f'Error: {e}')
        else:
            messages.error(request, 'Formulario no válido.')
    else:
        form = SalidaArticuloForm()
    return render(request, 'salida.html', {'salidas': salidas, 'form': form})

#------------------------------------------------------------------

from .models import Inventario, OrdenSalida
from .forms import OrdenSalidaForm
from django.utils import timezone

def orden_salida(request):
    query = request.GET.get('q')
    ordenes_salida = OrdenSalida.objects.all().order_by('-fecha_y_hora')
    if query:
        ordenes_salida = ordenes_salida.filter(
            Q(nombre_de_articulo__nombre__icontains=query) |
            Q(numero_orden__icontains=query) |
            Q(unidad__icontains=query)
        )
    if request.method == "POST":
        form = OrdenSalidaForm(request.POST)
        if form.is_valid():
            orden_salida = form.save(commit=False)
            inventario = orden_salida.nombre_de_articulo
            if inventario.cantidad_disponible < orden_salida.cantidad:
                messages.error(request, "No hay suficiente cantidad en inventario.")
                return render(request, 'orden_salida.html', {'form': form, 'ordenes_salida': ordenes_salida})
            orden_salida.save()
            messages.success(request, 'La orden de salida se realizó correctamente')
            return redirect('orden_salida')
    else:
        form = OrdenSalidaForm()
    return render(request, 'orden_salida.html', {'form': form, 'ordenes_salida': ordenes_salida})

#------------------------------------------------------------------------

from django.shortcuts import render, redirect, get_object_or_404
from .models import Factura
from .forms import FacturaForm

def facturas(request):
    query = request.GET.get('q')
    facturas = Factura.objects.all()
    if query:
        facturas = facturas.filter(
            Q(clave_de_registro__icontains=query) |
            Q(numero_de_folio__icontains=query) |
            Q(concepto__icontains=query)
        )
    if request.method == 'POST':
        if 'delete' in request.POST:
            factura_id = request.POST.get('factura_id')
            factura = get_object_or_404(Factura, id=factura_id)
            factura.delete()
            messages.success(request, '¡La factura se eliminó con éxito!')
            return redirect('facturas')

        else:
            form = FacturaForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, '¡La factura se añadió con éxito!')
                return redirect('facturas')
    else:
        form = FacturaForm()

    facturas = Factura.objects.all().order_by('-fecha_de_factura')
    return render(request, 'facturas.html', {'form': form, 'facturas': facturas})

#------------------------------------------------------------------------


def reportes(request):
    return render(request, 'reportes.html')
def index(request):
    return render(request, 'index.html')
def aviso(request):
    return render (request, 'aviso.html')
def Header(request):
    return render(request, 'Header.html')


def Iniciar_Sesión(request):
    logout(request)
    return redirect('login')
def Cerrar_Sesión(request):
    logout(request)
    return redirect('login')

utaller/templates/aviso.html
<h1>CONTACTA CON TU ADMINISTRADOR</h1>

utaller/templates/entrada.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Entrada de Artículos</title>
    <link rel="stylesheet" href="{% static 'css/entrada.css' %}">
</head>
<header>
    {% include 'index.html' %}
</header>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="message">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="container">
        <h1>Entrada de Artículos</h1>
        <form method="post" action="{% url 'entrada' %}" class="form">
            {% csrf_token %}
            <label for="nombre_de_articulo">Nombre de Artículo:</label>
            {{ form.nombre_de_articulo }}<br>
            <label for="categoria">Categoría:</label>
            {{ form.categoria }}<br>
            <label for="unidad_de_medida">Unidad de Medida:</label>
            {{ form.unidad_de_medida }}<br>
            <label for="cantidad_disponible">Cantidad Disponible:</label>
            {{ form.cantidad_disponible }}<br>
            <button type="submit">Agregar Artículo</button>
        </form>
        <h2>Entradas Recientes</h2>
        <!-- Formulario de búsqueda -->
        <form class="form-bus" method="GET" action="">
            <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
            <button type="submit">Buscar</button>
        </form>
        <table class="entradas-table">
            <thead>
                <tr>
                    <th>Nombre de Artículo</th>
                    <th>Categoría</th>
                    <th>Unidad de Medida</th>
                    <th>Cantidad Disponible</th>
                    <th>Fecha y Hora</th>
                </tr>
            </thead>
            <tbody>
                {% for entrada in entradas %}
                <tr>
                    <td>{{ entrada.nombre_de_articulo }}</td>
                    <td>{{ entrada.get_categoria_display }}</td>
                    <td>{{ entrada.get_unidad_de_medida_display }}</td>
                    <td>{{ entrada.cantidad_disponible }}</td>
                    <td>{{ entrada.fecha_y_hora }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!----------------------------------------------------------------------------------->

    <head>
        <!-- BotUI CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/botui/build/botui.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/botui/build/botui-theme-default.css">
    </head>
    </style>
    <!-- BotUI Container -->
    <div class="botui-app-container" id="botui-app">
        <bot-ui></bot-ui>
        <div class="back-button" id="back-button">&larr;</div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/botui/build/botui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>

    <script>

        var botui = new BotUI('botui-app');

        function showInitialMessage() {
            botui.message.bot({
                delay: 1000,
                content: 'Hola, soy el asistente virtual. ¿En qué puedo ayudarte?'
            }).then(function () {
                return botui.action.button({
                    delay: 1000,
                    action: [
                        { text: '¿Qué es esta página?', value: 'info' },
                        { text: '¿Cómo puedo agregar un artículo?', value: 'add_item' },
                        { text: 'Contactar soporte', value: 'contact' }
                    ]
                });
            }).then(handleResponse);
        }
        function handleResponse(res) {
            document.getElementById('back-button').style.display = 'block'; // Muestra el botón de regreso
            if (res.value === 'info') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Esta es la página de entrada de artículos donde puedes registrar nuevos artículos en el inventario.'
                });
            } else if (res.value === 'add_item') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Para agregar un artículo, completa el formulario y haz clic en "Agregar Artículo".'
                });
            } else if (res.value === 'contact') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Para contactar con soporte, envía un correo a soporte@example.com'
                });
            }
        }
        document.getElementById('back-button').addEventListener('click', function () {
            botui.message.removeAll(); // Elimina todos los mensajes
            showInitialMessage(); // Muestra el mensaje inicial nuevamente
            this.style.display = 'none'; // Oculta el botón de regreso
        });

        showInitialMessage();
        // Scroll to top after page load
        window.onload = function () {
            window.scrollTo(0, 0);
        }
    </script>


    <style>
        .botui-app-container {
            position: fixed;
            bottom: 0;
            right: 0;
            width: 200px;
            /* Aumenta el ancho del contenedor */
            height: 400px;
            /* Altura del contenedor */
            overflow-y: auto;
            /* Agrega desplazamiento vertical si el contenido supera la altura */
            border-radius: 15px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: white;
            /* Añade un fondo blanco para mejor visibilidad */

        }

        .botui-actions-buttons {
            width: 50%;
            /* Ajusta el ancho de los botones */
            position: fixed;
            align-items: center;
            /* Centra los botones en el contenedor */
        }

        .back-button {
            display: none;
            /* Oculta el botón de regreso inicialmente */
            width: 50px;
            height: 50px;
            background-color: #4c535a;
            color: white;
            text-align: center;
            line-height: 50px;
            border-radius: 50%;
            position: absolute;
            bottom: 10px;
            right: 10px;
            cursor: pointer;
        }
    </style>

</body>

</html>

utaller/templates/gestionex.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Inventario</title>
    <link rel="stylesheet" href="{% static 'css/gestionex.css' %}">
</head>
<header>
    {% include 'index.html' %}
</header>
<body>
    <div class="container">
        <h1>Inventario Actual</h1>
        <!-- Formulario de búsqueda -->
        <form method="GET" action="">
            <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
            <button type="submit">Buscar</button>
        </form>
        <table class="inventario-table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Categoría</th>
                    <th>Unidad de Medida</th>
                    <th>Cantidad Disponible</th>
                </tr>
            </thead>
            <tbody>
                {% for item in inventario %}
                <tr>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.get_categoria_display }}</td>
                    <td>{{ item.get_unidad_de_medida_display }}</td>
                    <td>{{ item.cantidad_disponible }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

utaller/templates/reportes.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reportes</title>
</head>


<body>


</body>

</html>

utaller/templates/salida.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Salida de Artículos</title>
    <link rel="stylesheet" href="{% static 'css/salida.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/botui/build/botui.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/botui/build/botui-theme-default.css">
</head>
<header>
    {% include 'index.html' %}
</header>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="message">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="container">
        <h1>Salida de Artículos</h1>
        <form method="post" action="{% url 'salida' %}" class="form">
            {% csrf_token %}
            <label for="nombre_de_articulo">Artículo de Entrada:</label>
            {{ form.nombre_de_articulo }}<br>
            <label for="numero_orden">Número de Orden:</label>
            {{ form.numero_orden }}<br>
            <label for="unidad">Unidad:</label>
            {{ form.unidad }}<br>
            <label for="cantidad">Cantidad:</label>
            {{ form.cantidad }}<br>
            <label for="departamento">Departamento:</label>
            {{ form.departamento }}<br>
            <button type="submit">Registrar Salida</button>
        </form>
        <h2>Salidas Recientes</h2>
        <!-- Formulario de búsqueda -->
        <form class="form-bus" method="GET" action="">
            <input type="text" name="q" placeholder="Buscar..." value="{{ request.GET.q }}">
            <button type="submit">Buscar</button>
        </form>
        <table class="salidas-table">
            <thead>
                <tr>
                    <th>Artículo de Entrada</th>
                    <th>Número de Orden</th>
                    <th>Unidad</th>
                    <th>Cantidad</th>
                    <th>Departamento</th>
                    <th>Fecha y Hora</th>
                </tr>
            </thead>
            <tbody>
                {% for salida in salidas %}
                <tr>
                    <td>{{ salida.nombre_de_articulo.nombre }}</td>
                    <td>{{ salida.numero_orden }}</td>
                    <td>{{ salida.unidad }}</td>
                    <td>{{ salida.cantidad }}</td>
                    <td>{{ salida.get_departamento_display }}</td>
                    <td>{{ salida.fecha_y_hora_salida }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- BotUI Container -->
    <div class="botui-app-container" id="botui-app">
        <bot-ui></bot-ui>
        <div class="back-button" id="back-button">&larr;</div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/botui/build/botui.min.js"></script>
    <script>
        var botui = new BotUI('botui-app');

        function showInitialMessage() {
            botui.message.bot({
                delay: 1000,
                content: 'Hola, soy el asistente virtual. ¿En qué puedo ayudarte?'
            }).then(function () {
                return botui.action.button({
                    delay: 1000,
                    action: [
                        { text: '¿Qué es esta página?', value: 'info' },
                        { text: '¿Cómo puedo dar salida a un artículo?', value: 'add_item' },
                        { text: 'Contactar soporte', value: 'contact' }
                    ]
                });
            }).then(handleResponse);
        }

        function handleResponse(res) {
            document.getElementById('back-button').style.display = 'block'; // Muestra el botón de regreso
            if (res.value === 'info') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Esta es la página de salida de artículos donde puedes registrar nuevas salidas de inventario.'
                });
            } else if (res.value === 'add_item') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Para dar salida a un artículo, completa el formulario y haz clic en "Registrar Salida".'
                });
            } else if (res.value === 'contact') {
                botui.message.bot({
                    delay: 1000,
                    content: 'Para contactar con soporte, envía un correo a soporte@example.com'
                });
            }
        }

        document.getElementById('back-button').addEventListener('click', function () {
            botui.message.removeAll(); // Elimina todos los mensajes
            showInitialMessage(); // Muestra el mensaje inicial nuevamente
            this.style.display = 'none'; // Oculta el botón de regreso
        });

        showInitialMessage();
        // Scroll to top after page load
        window.onload = function () {
            window.scrollTo(0, 0);
        }
    </script>

    <style>
        .botui-app-container {
            position: fixed;
            bottom: 0;
            right: 0;
            width: 200px;
            /* Aumenta el ancho del contenedor */
            height: 400px;
            /* Altura del contenedor */
            overflow-y: auto;
            /* Agrega desplazamiento vertical si el contenido supera la altura */
            border-radius: 15px;
            margin: -5px auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .botui-actions-buttons {
            width: 50%;
            /* Ajusta el ancho de los botones */
            position: fixed;
            align-items: center;
            /* Centra los botones en el contenedor */
        }

        .back-button {
            display: none;
            /* Oculta el botón de regreso inicialmente */
            width: 50px;
            height: 50px;
            background-color: #4c535a;
            color: white;
            text-align: center;
            line-height: 50px;
            border-radius: 50%;
            position: absolute;
            bottom: 10px;
            right: 10px;
            cursor: pointer;
        }
    </style>

</body>

</html>